apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
    method: fromcode
    another: label
  name: nginx-yaml2
spec:
  containers:
  - image: nginx
    name: nginx
    
